server.port: 8880

camunda:
  bpm:
    admin-user:
      id: user
      password: userSecret
      firstName: User
    filter:
      create: All tasks
    database:
      type: mssql

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=camunda
    username: camunda
    password: camunda
