camunda:
  bpm:
    admin-user:
      id: user
      password: userSecret
      firstName: User
    filter:
      create: All tasks
    database:
      type: h2

spring:
  datasource:
    url: jdbc:h2:file:C:/Projects/camunda
    username: sa
    password: 
